version: '3'
services:
  php-fpm:
    tty: true
    image: 'docker.io/bitnami/php-fpm:latest'
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www
      - ./services/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - internal
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    networks:
      - internal
  redis:
    image: redis:alpine
    container_name: redis
    ports:
     - 6379:6379
    volumes:
      - ./services/redis/data:/data
      # - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - internal
  memcached:
    image: 'bitnami/memcached:latest'
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - internal
  mysql:
    image: mysql:latest
    container_name: mysq
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'changeme'
      MYSQL_ROOT_PASSWORD: 'changeme'
    ports:
      - 3306:3306
    volumes:
      - ./services/mysql/data:/var/lib/mysql
    networks:
      - internal
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01
    volumes:
      - ./services/elasticsearch/data:/usr/share/elasticsearch/data
      - ./services/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbit
    hostname: "rabbit"
    volumes:
      - "./services/rabbit/data:/var/lib/rabbitmq"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - internal
  cerebro:
    image: yannart/cerebro:latest
    container_name: cerebro
    environment:
      - CEREBRO_PORT=9001
    ports:
      - "9001:9001"
    networks:
      - internal
networks:
  internal:
    driver: bridge

